### ISSUE TITLE
Documentation (CONTRIBUTING.md): How to use Pylint, flake8 and tox

### ISSUE THREAD

**Issue by avara1986** [python-microservices/pyms#168]
Update CONTRIBUTING.md with information about linters and tools and ways of use these:
- Pylint: link to official documentation, how can i execute the command, benefits of pylintrc
- Flake8: link to official documentation, how can i execute the command, benefits of define params in [setup.cfg](https://github.com/python-microservices/pyms/blob/master/setup.cfg#L7)
- Tox: link to official documentation
- Mypy: link to official documentation, benefits of define params in setup.cfg (PR open to add this tool)
- setup.cfg: what's mean this file

**Comment by jabhishek87** [comment]
can you assign it to me  can work

**Comment by jabhishek87** [comment]
@avara1986 can you describe briefly what neds to be done , i see tox already presen in [contributing.md](https://github.com/python-microservices/pyms/blob/master/CONTRIBUTING.md)

**Comment by avara1986** [comment]
@jabhishek87 i do this! thank you!
