### ISSUE TITLE
config.yml generator, command

### ISSUE THREAD

**Issue by avara1986** [python-microservices/pyms#169]
Create a command to ask the user the configuration that he wants and generate a config.yml

Basic Flask config:
```
  config:
    DEBUG: true
    TESTING: false
    APP_NAME: "Python Microservice"
    APPLICATION_ROOT: ""
```

Input: do you want to use request? (Y/n) Y
```
pyms:
  services:
    requests:
      data: ""
  config:
    DEBUG: true
    TESTING: false
    APP_NAME: "Python Microservice"
    APPLICATION_ROOT: ""
```

Input: do you want to use swagger? (Y/n) Y
```
pyms:
  services:
    requests:
      data: ""
    swagger:
      path: ""
      file: "swagger.yaml"
  config:
    DEBUG: true
    TESTING: false
    APP_NAME: "Python Microservice"
    APPLICATION_ROOT: ""
```

**Comment by path2himanshu** [comment]
Hey @avara1986 - I want to contribute to the project. Can you please assign this issue too me?

**Comment by avara1986** [comment]
Thank you @path2himanshu ! ^^ Don't forget to register in https://hacktoberfest.digitalocean.com/ :+1:
