### ISSUE TITLE
Improve README wording and fix trailing whitespaces

### ISSUE THREAD

**Issue by ibLeDy** [python-microservices/pyms#172]
**Is your feature request related to a problem? Please describe.**

I would like to improve the wording of the README, for example: 
- [Line 30](https://github.com/python-microservices/pyms/blob/master/README.md#L30): how use -> how _to_ use
- [Line 34](https://github.com/python-microservices/pyms/blob/master/README.md#L34): started to create microservice -> started _creating a_ microservice
- [Line 45](https://github.com/python-microservices/pyms/blob/master/README.md#L45): can`t -> _can't_
- [Line 98](): This initialization inject -> This initialization _injects_
- [Line 99](): like typical -> like _a_ typical
- [Line 103](): Initialize Flask instance -> Initialize _a_ Flask instance
- [Line 109](): return the flask instance and you can interact with it -> _returns_ the flask instance, _which you can interact with_
- [Line 116](): This command use -> This command _uses_
- [Line 146](): finish to introduce -> finish _introducing_

I also see some warnings about not following Markdown convention rules, i'm using VSCode with the [Markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) extension, which displays the following formatting warnings:

![2020-10-01_10-57-03](https://user-images.githubusercontent.com/45886240/94789664-7cb3af00-03d5-11eb-80e0-ebd107c05e06.png)

_Note: they are convention warnings, sometimes you do want a specific formatting and it's okay to not follow these rules_

They were also a lot of `MD009/no-trailing-spaces: Trailing spaces [Expected: 0 or 2; Actual: 1]`, which is a common issue if trailing whitespaces are not trimmed before commiting. In Markdown, two trailing whitespaces make a newline (useful to separate paragraphs). I also would like to fix these.

_If you don't want to separate paragraphs with the spaces method, i highly recomment turning on `Trim Trailing Whitespace` which is available in all of the common text editors/IDEs, (for example the setting is called `files.trimTrailingWhitespace` in VSCode and `trim_trailing_white_space_on_save` on Sublime)_

**Describe the solution you'd like**
I would like to sumbit a PR to improve the wording and fix the trailing whitespaces. I would optionally fix _some_ or _all_ of the Markdown convention warnings, if you want to.

**Describe alternatives you've considered**

**Additional context**

**Comment by avara1986** [comment]
awesome issue @ibLeDy ! :heart: 
Submit a PR if you like! Thanks a lot for the explanation :heart_eyes:

**Comment by ibLeDy** [comment]
Thanks!

Do you want me to fix the Markdown ones too?

If the answer is yes, the `MD026` ([L96](https://github.com/python-microservices/pyms/blob/master/README.md#L96)) may be the only one that you may want to keep as it is, so unless you specify that you want it fixed too, i will omit that one.

**Comment by avara1986** [comment]
Hi, could be perfect to fix the Markdown too :smile: 

About `MD026` ([L96](https://github.com/python-microservices/pyms/blob/master/README.md#L96)), it is a bug, the L96 must be a H2, not a H3
