### ISSUE TITLE
Documentation: Introduction to Microservices

### ISSUE THREAD

**Issue by avara1986** [python-microservices/pyms#189]
PyMS is useful to build microservices with Flask. But, if someone want to contribute to PyMS, the first he needs is know how microservices work and the behavior

- Create in docs folder a new page with documentation about microservices:
  - Links to videos
  - Links to articles
- Explain what is a microservices

Could be ok create sections in different languages (english, spanish, etc)

**Comment by AmandaKhol** [comment]
Hi! I would like to contribute to this issue :-) Could I?
