### ISSUE TITLE
Support registration in Consul

### ISSUE THREAD

**Issue by Agalin** [python-microservices/pyms#190]
**Is your feature request related to a problem? Please describe.**
Would be nice to add support for registration in Consul. It can then be used as a configuration source for Prometheus for metrics scrapping. It's possible to configure manually now but standardized service would be an useful addition.

Consul can also be used as a service discovery (so would be a possible extension of `requests` integration as well) and key-value store (`flask-consulate` actually uses it as a configuration service).

**Describe the solution you'd like**
Add service that would wrap `consulate` package.

**Describe alternatives you've considered**
There is `flask-consulate` package that aims to provide some of the described functionality but it's barely maintained, provides no wheel binaries (it's messing with build process behind corporate proxy due to direct setup.py call) and some functions overlap with those that should be a part of pyms (it seems to retry service calls).

**Additional context**
There are other service discovery tools available, like `Eureka` or cloud-specific providers which means that it should be as provider-agnostic as possible, similar to tracing supporting two collection servers already.

**Comment by avara1986** [comment]
Thanks @Agalin for your issues :smile: All your feature proposal are very interesting :+1:

**Comment by Agalin** [comment]
I'm just jealous of Spring Initializer where you can generate an app preconfigured for so many services... This project can be something similar for python.
