### ISSUE TITLE
Outdated docstrings

### ISSUE THREAD

**Issue by alexppg** [python-microservices/pyms#196]
**Describe the bug**
The docstrings on the [conf.py](https://github.com/python-microservices/pyms/blob/master/pyms/config/conf.py) file are outdated. It may happen in other files.

It seems difficult to maintain the scheme of the configuration file, since the structure may change over time. Maybe the structure should be defined in only one way and then be referenced around the project. And this can apply to any code on any docstring.

**Comment by avara1986** [comment]
@PandyTheBroh i resolved this issue in the PR #220 moving the documentation and docstrings to other repo, is it ok?
