### ISSUE TITLE
Documentation (CONTRIBUTING.md): add commit guide

### ISSUE THREAD

**Issue by avara1986** [python-microservices/pyms#198]
Add to contributing this link https://chris.beams.io/posts/git-commit/

**Comment by alexppg** [comment]
Maybe this is superseded by this, if you like it? https://github.com/python-microservices/pyms/issues/195

**Comment by avara1986** [comment]
No, no. Sorry, maybe i need to check and figure out commitizen. Do you can set `commitizen` as a mandatory way to commit new changes? I was thinking that is a tool to "help" when you commit anything, not a tool like black that force you to use this way of add changes

**Comment by alexppg** [comment]
They do have a way to check that the commit follows the stipulated format with `cz check`. Also they have a `pre-commit`. 

The way it works is that you create a configuration in the root of the project with the format you want and everybody just have to execute `git cz` and a interactive interface will appear asking questions.

It's not mandatory to use `cz` as is as long as your commit follows the format. I actually have it only as a git template, I don't use the interactive tool, for example.
