### ISSUE TITLE
Could we add Google Cloud KMS encryption

### ISSUE THREAD

**Issue by jeffny2015** [python-microservices/pyms#228]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

i see documentation say it supports but i dont see it implemented

**Comment by alexppg** [comment]
Where do you see it? In the docs it only talks about AWS's KMS, as far as I can see: https://python-microservices.github.io/encrypt_decryt_configuration/#2-encrypt-with-kms

**Comment by jeffny2015** [comment]
![image](https://user-images.githubusercontent.com/22873717/111827009-ff122b80-88ae-11eb-8331-b4c3d6582601.png)

**Comment by jeffny2015** [comment]
```
You can move this file to a Kubernetes secret, use Vault or encrypt the configuration with AWS KMS or **Google KMS**. We strongly recommend these way of encrypting/decrypting your configuration, but if you don't want a vendor locking option or you don't have the resources to use these methods, we provide a way to encrypt and decrypt your variables.
```

**Comment by jeffny2015** [comment]
i mean, could we add it ?

**Comment by avara1986** [comment]
We add this paragraph as recommendations and best practices to store configuration. In the nexts blocks describe the implementations that exists in PyMS. On the other hand, it could be confusing. We update this section, thanks @jeffny2015 for your contribution :)

**Comment by alexppg** [comment]
My bad, I didn't see it.
