### ISSUE TITLE
ModuleNotFoundError: No module named 'flask._compat' when trying to run server

### ISSUE THREAD

**Issue by Ileriayo** [python-microservices/pyms#234]
**Describe the bug**
I get a "ModuleNotFoundError: No module named 'flask._compat'" when I try to run a new pyms app.

**To Reproduce**
(Simply follow the documentation)
1. Scaffold a new app with 'pyms startproject' and choose the default options.
    * pyms startproject

2. Navigate into the new project and install dependencies using virtualenv
    * virtualenv venv
    * source venv/bin/activate
    * pip install -r requirements.txt

3. Run server
    * python manage.py runserver

**Expected behavior**
The app should not throw any error and be accessible on http://127.0.0.1:5000/[APPLICATION_ROOT]/

**Screenshots**
<img width="1280" alt="Screenshot 2021-07-03 at 15 16 41" src="https://user-images.githubusercontent.com/13166712/124357199-2ac4e180-dc12-11eb-911b-9c0618675653.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina

**Comment by sorXCode** [comment]
Update the `requirements.txt` to use any Flask version < 2...

_E.g_ add `Flask==1.1.4` to the top of the `requirements.txt` file

**Comment by Ileriayo** [comment]
Worked fine, thanks Victor!

**Comment by avara1986** [comment]
Created a Issue to fix that, thanks  @sorXCode @Ileriayo !

https://github.com/python-microservices/pyms/issues/235
