### ISSUE TITLE
Support encrypting secrets with kms

### ISSUE THREAD

**Issue by alexppg** [python-microservices/pyms#70]
**Is your feature request related to a problem? Please describe.**
When using a microservice, you usually need to set passwords for a database, for example. It would be useful to be able to encrypt it for security reasons. It might support many backends, but the first one may be used with AWS kms.
**Describe the solution you'd like**
Similar to this: https://github.com/zalando/spring-cloud-config-aws-kms#usage

**Comment by avara1986** [comment]
Inspired by this [article](https://nitratine.net/blog/post/encryption-and-decryption-in-python/), I added a agnostic method to encrypt the configuration without vendor locking. Maybe as first step it's ok, but, could be better expand this functionality with AWS KMS and GCP KMS? Anyone knows if with a [AES](https://en.wikipedia.org/wiki/Advanced_Encryption_Standard) it's OK or need more secure methods?

**Comment by alexppg** [comment]
It is good for this purpose. For this approach I think it would be nice to have very clear documentation on how to handle the key, since the operator will be the responsible to deploy them to the infrastructure and make sure that is not accessible by any bad actor.
