### ISSUE TITLE
Have an config reloader endpoint

### ISSUE THREAD

**Issue by alexppg** [python-microservices/pyms#71]
**Is your feature request related to a problem? Please describe.**
Sometimes you have a microservice which you want to change it's configuration. You could make the k8s deployment to recreate the cluster, but that wouldn't be need if the microservice had an endpoint which reloaded the configuration by itself.

**Describe the solution you'd like**
Implement an endpoint, for example `/-/reload` that will re-read the configuration.

**Comment by avara1986** [comment]
Created the method `Microservice.reload()` in PR #83. Next step, create the endpoint :muscle:

**Comment by avara1986** [comment]
@alexppg suggested: add a callback parameter to `Microservice.reload()` to expand the reload options :+1:

**Comment by avara1986** [comment]
Instruction:
Create an endpoint like the (Healthcheck)[https://github.com/python-microservices/pyms/blob/master/pyms/flask/healthcheck/healthcheck.py] and call `Microservice.reload()`

**Comment by lcd1232** [comment]
I'll do this

**Comment by alexppg** [comment]
@avara1986 with the development done, is possible to execute arbitrary orders when the endpoint is fetched? Like the example we talked, if I implement a ms that uses elasticsearch for example, and I reload the configuration, I might need to recreate the connection. Could I do it right now?

**Comment by avara1986** [comment]
Hi @alexppg, I think so,

The reload method has this code:
```
    def reload_conf(self):
        self.delete_services()
        self.config.reload()
        self.services = []
        self.init_services()
        self.crypt.config.reload()
        self.create_app()
```

and `create_app` method initialize Flask and `init_libs`. I suppose that your microservices initialize the configuration in `init_libs`, is it correct? If it's true, the elasticsearch connexion will be reloaded too :smile:

**Comment by alexppg** [comment]
Oh, I see. That makes sense. I don't see it documented, is it? If not, I'll create an issue.
