### ISSUE TITLE
Add a namespace to all used environment variables

### ISSUE THREAD

**Issue by alexppg** [python-microservices/pyms#89]
**Is your feature request related to a problem? Please describe.**
There's some environmental variables that pyms uses, like `CONFIGMAP_FILE` or `KEY_FILE`. Those are very generic names, if you see them without context, you might don't know why are they set and what are they purpose. 

**Describe the solution you'd like**
I propose to add a namespace to all variables, so `KEY_FILE` would be `PYMS_KEY_FILE`.

**Describe alternatives you've considered**
None.

**Additional context**
None.

If you guys agree, I might do this change myself.

**Comment by avara1986** [comment]
It`s a good idea :+1: 

In retrospective, the last refactor of the configuration, we did some bad actions. We changed all schema and not announce it. 

I propose add this change but preserve the old way and show a warning of deprecation in futures versions, what do you think?

**Comment by alexppg** [comment]
I agree. They should be removed at some time, but it doesn't have to break it at the next release. 
Also, a changelog should be generated on every release, with a special section with "breaking changes".

**Comment by rapejim** [comment]
I think I could make this issue.

**Comment by alexppg** [comment]
Nice, thanks @rapejim !
